


export const metadata = {
  title: 'Cell Game',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (<>
    {children}
  </>)
}