import '@/../style/css.css'
import authRepo from '@/../script/state/repository/auth'
import ClientLayoutWrapper from "@/dom/atom/ClientLayoutWrapper"


export const metadata = {
  title: 'Web App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const foundJWT:any = await authRepo.getJWT()
  console.log("foundJWT", foundJWT)
  const foundUser:any = !!foundJWT ? await authRepo.getUser(foundJWT) : null
  console.log("foundUser", foundUser)

  return (
    <html lang="en">
      <ClientLayoutWrapper session={{jwt:foundJWT,user:foundUser}}>
        <body className="ma-0 h-min-100vh" >
          {children}
        </body>
      </ClientLayoutWrapper>
    </html>
  )
}